package model;

import org.apache.jena.query.Query;
import org.apache.jena.query.QueryFactory;
import org.apache.jena.query.Syntax;

import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;
import java.awt.event.*;

public class PatternSearch extends javax.swing.JDialog
{
    private static final long serialVersionUID = 1L;

    public static String TITLE = "Query SPARQL";

    private javax.swing.JButton btCancel;
    private javax.swing.JButton btSearch;
    private JTextPane txtSparql;
    private int dialogResult = JOptionPane.CANCEL_OPTION;

    public void setQuery(String text)
    {
        txtSparql.setText(text);
    }
    public String getQuery()
    {
        return txtSparql.getText().trim();
    }
    public int getDialogResult()
    {
        return dialogResult;
    }

    /**
     * La fenetre permettant de saisir les mots clés
     * @param coordinates Les coordonnées des noeuds du graph
     * @param jDesktopPANE la fenetre principale
     */
    public PatternSearch() {
        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent arg0) {
                txtSparql.requestFocus();
            }
        });
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent arg0) {
                dialogResult = JOptionPane.CANCEL_OPTION;
            }
        });

        initComponents();
        setLocationRelativeTo(null);
        setTitle(TITLE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        btSearch = new javax.swing.JButton();
        btSearch.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e)
            {
                String query = getQuery();
                if(query.length() > 0)
                {
                    try
                    {
                        QueryFactory.parse(new Query(), query, null, Syntax.syntaxSPARQL_11);
                    }
                    catch(Exception ex)
                    {
                        JOptionPane.showMessageDialog(PatternSearch.this, ex.getMessage(), "Parse SPARQL", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
                dialogResult = JOptionPane.OK_OPTION;
                setVisible(false);
            }
        });

        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setPreferredSize(new Dimension(428, 250));

        btSearch.setText("Apply");

        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtSparql = new JTextPane();
        txtSparql.setBorder(new LineBorder(new Color(0, 0, 0)));

        JScrollPane scrollPane = new JScrollPane();
        scrollPane.setViewportView(txtSparql);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout( getContentPane() );
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btCancel)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btSearch)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(btCancel)
                                        .addComponent(btSearch))
                                .addContainerGap())
        );
        getContentPane().setLayout(jPanel1Layout);


        pack();
    }// </editor-fold>
    /**
     * Le bouton cancel
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        dialogResult = JOptionPane.CANCEL_OPTION;
        setVisible(false);
    }
}
